name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1

      - name: Install and Build ğŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          # npm cache clear --force
          yarn install
          yarn build
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          BRANCH: master # The branch the action should deploy to.
          FOLDER: public # The folder the action should deploy.
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: blog # The branch the action should deploy from.
      - name: Move index.html
        run: sudo mv public/index.html public/temp.html
      - name: DeployToMain
        uses: garygrossgarten/github-action-scp@release
        with:
          local: public
          remote: /root/myapp/www/
          # æ¶‰åŠåå®‰å…¨éšç§çš„ä¿¡æ¯ï¼Œä¸è¦æ˜æ–‡æš´éœ²åœ¨æ­¤æ–‡ä»¶ä¸­ï¼Œå› ä¸ºrepoå¾ˆå¯èƒ½æ˜¯å…¬å¼€çš„ï¼Œä¼šè¢«æ‰€æœ‰äººçœ‹è§
          # ${{ ... }} ä¼šåº”ç”¨ä½ åœ¨å¯¹åº”é¡¹ç›®è®¾ç½®ä¸­ï¼Œé…ç½®çš„å¯¹åº”seretsçš„é”®å€¼ä¿¡æ¯ï¼Œä»è€Œä¿æŠ¤ç§å¯†ä¿¡æ¯ä¸è¢«çœ‹åˆ°
          host: ${{ secrets.HOST }}
          port: ${{secrets.PORT}}
          username: ${{ secrets.USER }}
          privateKey: ${{ secrets.PEM }}
          # concurrency: 20
      - name: upload index.html
        uses: garygrossgarten/github-action-scp@release
        with:
          local: public/temp.html
          remote: /root/myapp/www/index.html
          host: ${{ secrets.HOST }}
          port: ${{secrets.PORT}}
          username: ${{ secrets.USER }}
          privateKey: ${{ secrets.PEM }}
